version: "3"
services:
  solr:
    image: solr:8.2
    ports:
      - "8983:8983"
    volumes:
      - ./test/data:/var/solr/data
      - ./test/logs:/opt/solr/logs
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - solrawler

  crawler:
    build: solrawler
    depends_on:
      - solr
    command: ["fiasko"]
    volumes:
      - ./test/spiders:/opt/solrawler/solrawler/spiders
